### ISSUE TITLE
Phenotype is sometimes a list

### ISSUE THREAD

**Issue by jmmcd** [jmmcd/PonyGE2#12]
The following parameters result in a best-of-run individual whose phenotype is a list, not a string.

'POPULATION_SIZE' : 3,
'GENERATIONS' : 1,
'RANDOM_SEED': 3

Other parameters as in the repo.

**Comment by jmmcd** [comment]
No, that was wrong. The list phenotypes won't appear as best of run unless something else is also broken (which it was in my repo). But they do appear, just not as best of run.

To see it, add this line at the bottom of individual.__init__() -- no need to change any parameters.

        print(type(self.phenotype))

I guess it happens with invalid individuals. But they should probably have phenotype=None, not a list.

**Comment by mikefenton** [comment]
Solved the list issue, invalid individuals were returning a phenotype as a list as it wasn't being joined. Invalids now have "None" phenotype
