### ISSUE TITLE
Need to add python program grammar examples

### ISSUE THREAD

**Issue by mikefenton** [jmmcd/PonyGE2#19]
We need to add a basic example of how to write python code in a grammar. This will also require a fitness function to exec the solution rather than using eval (code -vs- expressions). With the new regular expression grammar parser we can now use nice looking multi-line code. Bear in mind that the old indentation/new line style of def func():{<something>} has now changed to def func():{:<something>:}. We only need to create a simple example, nothing too fancy, but it showcases the capabilities of the method.

**Comment by jmmcd** [comment]
Added an example in 2ed75308ae7d32b69bd5d448bf52214b36a7a817

Not sure whether it fulfils "simple example, nothing too fancy" ;-)
