### ISSUE TITLE
Random number seed

### ISSUE THREAD

**Issue by jmmcd** [jmmcd/PonyGE2#2]
It looks like it's not being set correctly, or is being overwritten, or there are two RNG instances, or something.

**Comment by hembergerik** [comment]
Is it at `src/representation/tree.py` line 15? (I am not familiar enough to run the test suite and make a patch, but it seems like a suspicious line :-))

**Comment by jmmcd** [comment]
Yes, that line is clearly bad, and there are other places that need to be checked too. Please ignore this issue for now -- it's just so we can track things we know are broken.

**Comment by dvpfagan** [comment]
It is being set in a few places. We need to just remove all the seed
setting and place it in one place so we either set a seed or it uses the
system clock. There are a few other magic numbers floating about the code
that need to be set in parameters as well.

**Comment by dvpfagan** [comment]
Fixed this with commit 645309c9ad85d15be8bde092948a3f276dde4b93

**Comment by dvpfagan** [comment]
Fixed this with commit 645309c9ad85d15be8bde092948a3f276dde4b93
