### ISSUE TITLE
Allow for saving and reloading of state

### ISSUE THREAD

**Issue by mikefenton** [jmmcd/PonyGE2#22]
Periodically save the state of a run, e.g. entire population, current random state, population stats, cache. This should allow for runs to be re-loaded from a specific point if they crash (helps with really long runs). Easiest to save all info and data structures as a .mat file, can then re-load everything quickly and easily.

**Comment by mikefenton** [comment]
New module has been added in 

> src/utilities/algorithm/state

 which allows for the saving and re-loading of state using pickle. This allows the user to save a run at a particular point in time and to re-load that run from the saved state. Re-loaded runs will produce exactly the same results as the original version.

There is no actual implementation of the code yet, the module is simply there for the time being. Possibly best to discuss how best to include the functionality in the overall system rather than me just firing it in.

**Comment by mikefenton** [comment]
Could possibly include a try/except catch on the main search loop. If something goes wrong, save state?

**Comment by dvpfagan** [comment]
Easiest solution is to save the genotype at end of generation to file and
use numpy random as it provides a get state and load state for the random
number generator. All this should only be done if a
--save-intermediate-state flag is enabled

**Comment by mikefenton** [comment]
Now fully integrated. See commit 6eda0714e8e72ff239adc10c65de1939c2c1cb90.
