### ISSUE TITLE
Parameter BNF_GRAMMAR should be called GRAMMAR_FILE

### ISSUE THREAD

**Issue by jmmcd** [jmmcd/PonyGE2#29]
For consistency -- every other parameter has the same name: `--lower-case-option` translates to `params['UPPER_CASE_OPTION']`, but `--bnf-grammar` translates to `params['GRAMMAR_FILE']`.

I would just do it, but it will make all your old `parameters.txt` files unusable, i.e. before re-running an old experiment you'll need to `s/BNF_GRAMMAR/GRAMMAR_FILE` in the `parameters.txt` file.

We could keep the old name for compatibility, but document the new one -- any preferences?

**Comment by dvpfagan** [comment]
I say change it, it will cause a break with old files but is easily fixed
by editing a single thing in the properties files

Dave

**Comment by dvpfagan** [comment]
Properties.txt that is

**Comment by mikefenton** [comment]
Yeah gopher it. At this early stage I don't think many people are going to have parameters files saved that they will want to re-run anyway. As Dave says, it's an easy fix if they do want to re-run things.

**Comment by jmmcd** [comment]
Ok it was slightly more complicated. I've changed `--bnf_grammar` to `--grammar_file`. We still have both `params['BNF_GRAMMAR']` (which stores the grammar itself) and `params['GRAMMAR_FILE']` (which stores the filename). The former is not user-visible.
