### ISSUE TITLE
Crash when all individuals are invalid

### ISSUE THREAD

**Issue by jmmcd** [jmmcd/PonyGE2#33]
In stats.py, we have lines like:

```
        available = [i for i in individuals if not i.invalid]

        # Genome Stats
        genome_lengths = [len(i.genome) for i in available]
        stats['max_genome_length'] = max(genome_lengths)
```

(Also `min`, and `ave`.) These will throw an error if all individuals in a population are invalid. I've seen this a few times in the hill-climbing search loop, but not in the default search loop. Maybe there's some protection against all becoming invalid when running the default search loop?

**Comment by mikefenton** [comment]
Hmm, an interesting one. Crossover currently doesn't allow invalids to be created (i.e. crossover will continue until all children in the population are valid), but there's no such catch for mutation. Should we implement something like that?

**Comment by dvpfagan** [comment]
I got same issue with my initialiser stuff when I forgot to account for
unit productions

**Comment by jmmcd** [comment]
Probably the default should be to allow crossover to create invalids since that is the published algorithm. Maybe add switches `--no-crossover-invalids` and `--no-mutation-invalids`.

**Comment by mikefenton** [comment]
Switch added for --no_crossover_invalids. However, mutation is not quite so easy to put various checks in place (e.g. limitations on max depth/nodes/invalids) as the current mutation is done with a list(map()) function, necessitating a bit more thought to sort out.

**Comment by mikefenton** [comment]
Mutation now has the same checks as crossover. All checks have been moved to `utilities.representation.check_methods.check_inds`. Checks can be extended to suit.

**Comment by mikefenton** [comment]
Setting the default fitness is now the responsibility of each individual fitness function. By default, we have set the `default_fitness` value of each fitness function to `numpy.NaN`. This allows us to calculate population statistics over the entire population by filtering out these np.NaN values using numpy's `np.nanmax()`, `np.nanmin()`, and `np.nanmean()` functions. PonyGE will no longer crash if all individuals are invalid.

**Comment by dvpfagan** [comment]
We should state somewhere that invalids are excluded from stats.

**Comment by mikefenton** [comment]
All this info should be in the `README` I presume. RTFM issue...

**Comment by dvpfagan** [comment]
Yep, readme is fine just wanna make sure we do say it somewhere :D

**Comment by mikefenton** [comment]
Agreed. It's gonna take a fair while to ensure everything is in the `README`. When the code review is being done it might be an idea to check that every aspect is documented in the `README` somehow...

**Comment by dvpfagan** [comment]
Fingers crossed i get the pc running in the meeting room before then should
make code review a bit easier :D
