### ISSUE TITLE
We shouldn't quit

### ISSUE THREAD

**Issue by jmmcd** [jmmcd/PonyGE2#34]
We use `quit` in a few places, but we probably shouldn't, for two reasons:

* It would be nice to be able to use PonyGE2 as a library, i.e. importing it and using it, but not necessarily using ponyge.py as a command-line program. For example one might write a web server which runs GE and serves results. We don't want the server to quit! It would be better, when catching an error, to just re-raise it after printing and taking other appropriate action.

* `quit` and `exit` are for interactive use: http://stackoverflow.com/questions/19747371/python-exit-commands-why-so-many-and-when-should-each-be-used

**Comment by mikefenton** [comment]
Nearly all quits and exits have been changed to raise Exceptions. However, one quit remains, in stats.parse_stats.parse_opts. If you call `python stats.parse_stats.py --help` , it will print out the help message and then quit. Is there an alternative to this that does the same thing, but doesn't use quit/exit?

**Comment by dvpfagan** [comment]
We have talked about removing parse stats, as it isn't used in ponyge

**Comment by jmmcd** [comment]
Since `parse_stats` is a standalone program, the argument for not quitting doesn't apply.

(`parse_stats` also contains some functions which would be useful if imported to another program, and they shouldn't quit.)

**Comment by mikefenton** [comment]
So should we leave it as is? The only use of `quit()` is in the command line parser part of `parse_stats`, which is only used if the file is used as a standalone program. The main functions can be imported and used other functions with no adverse (i.e. quitting) effects.

**Comment by jmmcd** [comment]
Yup, seems fine as is.
