### ISSUE TITLE
unique_inds 0 and unused_search 100

### ISSUE THREAD

**Issue by jmmcd** [jmmcd/PonyGE2#36]
I'm seeing this in every run, I guess some tracker is not hooked up right:

```
  unique_inds :        	 0
  unused_search :      	 100.0
```

**Comment by mikefenton** [comment]
This is only the case if you don't specify --cache. The cache is turned off by default, and thus the length of the cache (`unique_inds`) is 0. The `unused_search` is calculated from the `unique_inds` value, so this will always be 100 if the cache is not used. I suppose we can just remove these two stats if the cache is not being used.

**Comment by mikefenton** [comment]
Fixed this in the latest commit: 7805ce40582e6a87e560861966fa9fd46ba27128.
