### ISSUE TITLE
"Correct" implementation of RHH/Sensible initialisation

### ISSUE THREAD

**Issue by mikefenton** [jmmcd/PonyGE2#38]
In our current implementation of RHH/Sensible initialisation, the "Grow" component builds random trees up to a maximum specified depth. Importantly, we do not _force_ any branch of the tree to reach that depth, meaning:
> Grow produces trees of irregular shapes and sizes because of random selection from the functions and terminals set.

This is directly in line with Ryan & Azad's description of Sensible/RHH initialisation (above quote taken from that paper). However, there has apparently been some doubt over whether or not the "Grow" portion of RHH should force at least one branch of the tree to the specified maximum depth. We should clarify this issue and decide exactly what to do.

It is important to note that RHH initialisation is inherently flawed in GE due to the use of grammars, as noted in [our paper on Position Independent Initialisation](http://dx.doi.org/10.1109/CEC.2016.7748331). Due to the randomness of the "Grow" component of RHH, GE will tend to produce very small trees if it isn't forced to do otherwise, regardless of the depth limit. This results in a high degree of duplication in the initialised population, meaning RHH in GE doesn't adequately cover the initial search space. This is also tied in very strongly with grammar design; more complex grammars mitigate this effect.

**Comment by jmmcd** [comment]
Decision: no consensus on what the "true" algorithm is. Let's leave it with NO forcing of any depth in Grow.

**Comment by jmmcd** [comment]
(PIGrow gives us a ramped operator with forcing depth of at least one branch (not just the left-most).
