### ISSUE TITLE
Classification error metric: module 'utilities.fitness.error_metric' has no attribute 'inverse_f1_score'.

### ISSUE THREAD

**Issue by mikefenton** [jmmcd/PonyGE2#43]

**Comment by mikefenton** [comment]
It seems the inverse_f1_score error metric has been changed to f1_score. Changing to f1_score brings up a different error:

TypeError: Singleton array True cannot be considered a valid collection.

**Comment by jmmcd** [comment]
Fixed in cb64e8c..bf3c570
