### ISSUE TITLE
Setting default fitness function to `supervised_learning` in the params dict and not using parameters file gives error.

### ISSUE THREAD

**Issue by mikefenton** [jmmcd/PonyGE2#53]
If the fitness function in the params dictionary is set to `supervised_learning` and no parameters file is used, the default `error_metric` is None, which throws an error when it is called. I have changed the default fitness func in the params dict to `regression`, which skirts this issue as the `regression` and `classification` fitness functions both set the correct error metrics in their respective inits, assuming the error metric is None already. This issue is simply a result of poor configuration choices, and is something that needs to be highlighted in the README.

**Comment by jmmcd** [comment]
Yes, that's better. `supervised_learning` is an abstract class, it makes no sense to instantiate it.
