### ISSUE TITLE
Datasets should be saved in individual folders in the overall `datasets` folder

### ISSUE THREAD

**Issue by mikefenton** [jmmcd/PonyGE2#56]
At present, all datasets are saved as text files in the `datasets` folder. Datasets are specified by name, e.g. `Dow` will specify the `Dow` datasets which are saved in `Dow-Test.txt` and `Dow-Train.txt`. Parsing in these datasets therefore requires a fair bit of hard-coding; we **require** that datasets be saved as `[NAME]-Test.txt` and `[NAME]-Train.txt`. Provision is not made for any other eventuality. We even have a function for reading in a single dataset and splitting it in to training and testing data, but it isn't used anywhere.

If we change this so each dataset is saved in its own folder within the overall `datasets` folder, then we can bypass a lot of hard coding and open up a lot more functionality. For example, instead of the `Dow` datasets being are saved directly in the `datasets` folder under `Dow-Test.txt` and `Dow-Train.txt`, they should be saved in `datasets/Dow` under `Test` and `Train` (the file extensions don't matter). This way when a dataset name is specified, it just searches directly for that folder, i.e. specifying the dataset name simply specifies the name of the folder containing the desired datasets. Upon reading the contents of that folder, we can then determine if there are two files (i.e. Training and Testing data), or one single file (to be split into training and testing data).

**Comment by jmmcd** [comment]
Yeah this would be better.

**Comment by mikefenton** [comment]
Done.
