### ISSUE TITLE
Classification error metric from sklearn not working properly

### ISSUE THREAD

**Issue by mikefenton** [jmmcd/PonyGE2#58]
If you run PonyGE with the argument `--parameters classification.txt` you get the following non-fatal error from the fitness function:

`UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.`

All fitnesses are returned as 0.

**Comment by jmmcd** [comment]
Fitness is 0 only for trivial individuals which return a constant <0. Will ignore the warning though.
