### ISSUE TITLE
Initialisation of duplicate individuals 

### ISSUE THREAD

**Issue by mikefenton** [jmmcd/PonyGE2#8]
Currently for ramped half-half initialisation we can produce duplicate phenotypes during the initialisation process. We start the ramping depth from a level where sufficient unique trees are known to exist, however we don't check how many unique "full" trees exist at each depth. The issue is that there could be sufficient unique trees at depth n, but insufficient unique _full_ trees at depth n. Therefore, some duplicate trees/phenotypes may be observed during RHH initialisation.

**Comment by jmmcd** [comment]
This is a fault of the RHH/Sensible Initialisation, not our fault. We'll add a parameter to let the user control min ramp depth, instead of inferring it from the number of unique inds at each depth (and pop size).
